<?php
error_reporting(0);
define('WEBROOT_PATH','/phpEasyProject/');
define('DATABASETYPE','mysql5');
define('DBHOST','localhost');
define('DBNAME','phpeasyProject');
define('DBUSER','root');
define('DBPASSWORD','root');
define('DBPREFIX','easy');
define('DEFAULTLANGUAGE','en');
define('TAETMINSTEP','15');
define('DEVELOPMENT',false);
define('UTFEXPICIT',true);
define('RECORDPERPAGE',50);
?>
